version: '3.9'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: files
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/files
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db
