server:
  servlet:
    context-path: /api/v1
  port: 8088
  tomcat:
    uri-encoding: UTF-8
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/files?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&character_set_server=UTF-8
    username: root
    password: root
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
    maximumPoolSize: 20
    connectionTimeout: 3600000
    idleTimeout: 600000
    minimumIdle: 5
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    hibernate:
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
